export interface pokemonsInfo {
    abilities?: [],
    baseExperience?: number,
    forms?: [],
    gameIndices?: [],
    height?: number,
    heldItems?: [],
    id?: number,
    isDefault?: boolean,
    locationAreaEncounters?: string,
    moves?: [],
    name?: string,
    order?: number,
    pastTypes?: [],
    species?: {},
    sprites?: {
        back_default?: string,
        back_female?: string,
        back_shiny?: string,
        back_shiny_female?: string,
        front_default?: string,
        front_female?: string,
        front_shiny?: string,
        front_shiny_female?: string,
    },
    stats?: [{}],
    types?: [{}],
    weight: number 
}